// Hand-authored usage notes for the semantic color tokens.
// (The Figma DTCG export carries no $description; these follow the Untitled UI
//  conventions + the token naming. Edit freely — not auto-generated.)
export const usage = {
  // ---- Text ----
  'text-primary': 'Chữ chính: tiêu đề, nội dung quan trọng nhất.',
  'text-primary_on-brand': 'Chữ chính khi đặt trên nền brand đậm.',
  'text-secondary': 'Chữ phụ: label form, mô tả, nhãn.',
  'text-secondary_hover': 'Trạng thái hover của chữ phụ.',
  'text-secondary_on-brand': 'Chữ phụ trên nền brand.',
  'text-tertiary': 'Chữ bổ trợ: help text, hint, chú thích.',
  'text-tertiary_hover': 'Hover của chữ bổ trợ.',
  'text-tertiary_on-brand': 'Chữ bổ trợ trên nền brand.',
  'text-quaternary': 'Chữ mờ nhất: metadata, timestamp.',
  'text-quaternary_on-brand': 'Chữ cấp 4 trên nền brand.',
  'text-white': 'Chữ trắng cố định (không đổi theo mode).',
  'text-disabled': 'Chữ ở trạng thái vô hiệu hoá.',
  'text-placeholder': 'Chữ placeholder trong ô nhập.',
  'text-placeholder_subtle': 'Placeholder nhạt hơn (input phụ).',
  'text-brand-primary': 'Chữ nhấn brand đậm nhất.',
  'text-brand-secondary': 'Chữ brand cấp 2.',
  'text-brand-tertiary': 'Link / chữ brand phổ biến (text link).',
  'text-brand-tertiary_alt': 'Biến thể của chữ brand cấp 3.',
  'text-error-primary': 'Chữ lỗi: thông báo lỗi, validation.',
  'text-error-primary_hover': 'Hover của chữ lỗi.',
  'text-warning-primary': 'Chữ cảnh báo.',
  'text-success-primary': 'Chữ thành công.',

  // ---- Border ----
  'border-primary': 'Viền mặc định: input, card, divider chính.',
  'border-secondary': 'Viền phụ nhạt hơn: chia khối, card.',
  'border-secondary_alt': 'Viền phụ dạng alpha (đè trên ảnh/nền màu).',
  'border-tertiary': 'Viền rất nhạt: phân tách tinh tế.',
  'border-disabled': 'Viền phần tử vô hiệu hoá.',
  'border-disabled_subtle': 'Viền disabled nhạt hơn.',
  'border-brand': 'Viền brand: input focus, phần tử được chọn.',
  'border-brand_alt': 'Biến thể viền brand.',
  'border-error': 'Viền lỗi: input không hợp lệ.',
  'border-error_subtle': 'Viền lỗi nhạt.',
  'border-success': 'Viền thành công.',
  'border-success_subtle': 'Viền thành công nhạt.',

  // ---- Foreground (icons / graphics) ----
  'fg-primary': 'Icon / đồ hoạ chính.',
  'fg-secondary': 'Icon phụ.',
  'fg-secondary_hover': 'Hover icon phụ.',
  'fg-tertiary': 'Icon bổ trợ (mờ hơn).',
  'fg-tertiary_hover': 'Hover icon bổ trợ.',
  'fg-quaternary': 'Icon mờ nhất.',
  'fg-quaternary_hover': 'Hover icon cấp 4.',
  'fg-white': 'Icon trắng cố định.',
  'fg-disabled': 'Icon vô hiệu hoá.',
  'fg-disabled_subtle': 'Icon disabled nhạt.',
  'fg-brand-primary': 'Icon brand chính.',
  'fg-brand-primary_alt': 'Biến thể icon brand chính.',
  'fg-brand-secondary': 'Icon brand cấp 2.',
  'fg-brand-secondary_alt': 'Biến thể icon brand cấp 2.',
  'fg-brand-secondary_hover': 'Hover icon brand cấp 2.',
  'fg-error-primary': 'Icon lỗi.',
  'fg-error-secondary': 'Icon lỗi cấp 2.',
  'fg-warning-primary': 'Icon cảnh báo.',
  'fg-warning-secondary': 'Icon cảnh báo cấp 2.',
  'fg-success-primary': 'Icon thành công.',
  'fg-success-secondary': 'Icon thành công cấp 2.',

  // ---- Background ----
  'bg-primary': 'Nền chính của trang / surface.',
  'bg-primary_alt': 'Nền chính thay thế (đổi theo mode).',
  'bg-primary_hover': 'Hover trên nền chính.',
  'bg-primary-solid': 'Nền đặc tương phản (vd tooltip đậm).',
  'bg-secondary': 'Nền phụ: section, sidebar, card.',
  'bg-secondary_alt': 'Nền phụ thay thế.',
  'bg-secondary_hover': 'Hover nền phụ.',
  'bg-secondary_subtle': 'Nền phụ rất nhạt.',
  'bg-secondary-solid': 'Nền phụ đặc.',
  'bg-tertiary': 'Nền cấp 3: vùng chìm, well.',
  'bg-quaternary': 'Nền cấp 4 đậm hơn.',
  'bg-active': 'Nền item đang active / được chọn.',
  'bg-disabled': 'Nền phần tử vô hiệu hoá.',
  'bg-disabled_subtle': 'Nền disabled nhạt.',
  'bg-overlay': 'Nền overlay / backdrop của modal.',
  'bg-brand-primary': 'Nền brand nhạt: badge, highlight.',
  'bg-brand-primary_alt': 'Biến thể nền brand nhạt.',
  'bg-brand-secondary': 'Nền brand cấp 2.',
  'bg-brand-solid': 'Nền brand đặc: nút primary.',
  'bg-brand-solid_hover': 'Hover nút brand primary.',
  'bg-brand-section': 'Nền mảng brand lớn (section/hero).',
  'bg-brand-section_subtle': 'Nền mảng brand nhạt hơn.',
  'bg-error-primary': 'Nền lỗi nhạt: alert lỗi.',
  'bg-error-secondary': 'Nền lỗi cấp 2.',
  'bg-error-solid': 'Nền lỗi đặc: nút destructive.',
  'bg-error-solid_hover': 'Hover nút destructive.',
  'bg-warning-primary': 'Nền cảnh báo nhạt.',
  'bg-warning-secondary': 'Nền cảnh báo cấp 2.',
  'bg-warning-solid': 'Nền cảnh báo đặc.',
  'bg-success-primary': 'Nền thành công nhạt.',
  'bg-success-secondary': 'Nền thành công cấp 2.',
  'bg-success-solid': 'Nền thành công đặc.',

  // ---- Effects (focus & shadows) ----
  'focus-ring': 'Vòng focus (bàn phím) màu brand quanh phần tử.',
  'focus-ring-error': 'Vòng focus cho trạng thái lỗi.',
  'shadow-xs': 'Elevation nhỏ nhất: input, ô nhỏ.',
  'shadow-sm_01': 'Bóng nhỏ (lớp 1): button, card nhẹ.',
  'shadow-sm_02': 'Bóng nhỏ (lớp 2) — chồng với sm_01.',
  'shadow-md_01': 'Bóng vừa (lớp 1): card nổi, dropdown.',
  'shadow-md_02': 'Bóng vừa (lớp 2).',
  'shadow-lg_01': 'Bóng lớn (lớp 1): popover, menu.',
  'shadow-lg_02': 'Bóng lớn (lớp 2).',
  'shadow-lg_03': 'Bóng lớn (lớp 3).',
  'shadow-xl_01': 'Bóng rất lớn (lớp 1): modal nhỏ.',
  'shadow-xl_02': 'Bóng rất lớn (lớp 2).',
  'shadow-xl_03': 'Bóng rất lớn (lớp 3).',
  'shadow-2xl_01': 'Bóng cực lớn (lớp 1): modal, dialog.',
  'shadow-2xl_02': 'Bóng cực lớn (lớp 2).',
  'shadow-3xl_01': 'Bóng tối đa (lớp 1): overlay lớn.',
  'shadow-3xl_02': 'Bóng tối đa (lớp 2).',
  'shadow-skeumorphic-inner': 'Bóng trong (inset) tạo chiều sâu khối.',
  'shadow-skeumorphic-inner-border': 'Viền trong đi kèm bóng skeuomorphic.',
  'shadow-main-centre-md': 'Bóng toả đều quanh phần tử (vừa).',
  'shadow-main-centre-lg': 'Bóng toả đều quanh phần tử (lớn).',
  'shadow-overlay-lg': 'Bóng lớn cho overlay / modal.',
  'shadow-grid-md': 'Bóng cho ô lưới / card trong grid.',
};
